changed

diff --git a/.github/workflows/update-task-status.yml b/.github/workflows/update-task-status.yml
--- a/.github/workflows/update-task-status.yml
+++ b/.github/workflows/update-task-status.yml
@@ -17,14 +17,13 @@ jobs:
         run: |
           # Extract the ClickUp Task ID from the pull request description
           PR_BODY="${{ github.event.pull_request.body }}"
-          CLICKUP_URL=$(grep -o -m1 'https://app.clickup.com/t/[A-Za-z0-9]\+' <<< $(echo "$PR_BODY" | sed 's/)/\\)/g'))
-          if [[ $CLICKUP_URL =~ /t/([A-Za-z0-9]+) ]]; then
-           CU_TASK_ID="${BASH_REMATCH[1]}"
-           echo "::set-output name=cu_task_id::$CU_TASK_ID"
-           echo "$CU_TASK_ID"
+          # Use a regex to match the ClickUp task URL and capture the task ID
+          if [[ $PR_BODY =~ https://app.clickup.com/t/([0-9]+) ]]; then
+            CU_TASK_ID="${BASH_REMATCH[1]}"
+            echo "::set-output name=cu_task_id::$CU_TASK_ID"
+            echo "$CU_TASK_ID"
           else
-           echo "ClickUp task ID not found in the pull request description."
-           exit 1  # Exit with an error code to stop the workflow
+            echo "ClickUp task ID not found in the pull request description."
+            exit 1  # Exit with an error code to stop the workflow
           fi
-
-      
+               
